module PayTrace
  module API
    class ResponseCode
      PASSWORD_UPDATED = 100 
      TRANSACTION_APPROVED = 101  
      TRANSACTION_NOT_APPROVED = 102  
      TRANSACTION_VOIDED = 103  
      TRANSACTION_APPROVED_TEST = 104
      TRANSACTION_NOT_APPROVED_TEST = 105
      TRANSACTION_REFUNDED = 106 
      TRANSACTION_NOT_REFUNDED = 107 
      TRANSACTION_REFUNDED_TEST = 108
      TRANSACTION_VOIDED = 109 
      TRANSACTION_NOT_VOIDED = 110 
      TRANSACTION_VOIDED_TEST = 111
      TRANSACTION_CAPTURED = 112 
      TRANSACTION_NOT_CAPTURED = 113 
      TRANSACTION_CAPTURED_TEST = 114
      TRANSACTION_FORCED = 115 
      TRANSACTION_NOT_FORCED = 116 
      TRANSACTION_FORCED_TEST = 117
      TRANSACTION_STORED = 118 
      CHECK_PROCESSED = 120 
      CHECK_PROCESSED_TEST = 121
      CHECK_REFUNDED = 122  
      CHECK_REFUNDED_TEST = 123
      CHECK_MANAGED = 124 
      CHECK_NOT_PROCESSED = 125 
      RECIEPT_EMAILED = 149 
      REOCCURING_TRANSACTION_CREATED = 150  
      REOCCURING_TRANSACTION_UPDATED = 151  
      REOCCURING_TRANSACTION_DELETED = 152  
      EXPORT_REOCCURING_TRANSACTION_SUCCESS = 155
      CUSTOMER_PROFILE_CREATED = 160
      CUSTOMER_PROFILE_UPDATED = 161
      CUSTOMER_PROFILE_DELETED = 162
      LEVEL_3_ADDED = 170
      LEVEL_3_ADDED = 171
      TRANSACTION_BATCH_SETTLED = 175
      TRANSACTION_AMOUNT_ADJUSTED = 180
    end
  end
end